//
//  MainPageRouter.swift
//  Lodos Movies
//
//  Created by Tuğrul on 13.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainPageRoutingLogic {
    func routeToMovieDetail()
}

protocol MainPageDataPassing {
    var dataStore: MainPageDataStore? { get }
}

class MainPageRouter: NSObject, MainPageRoutingLogic, MainPageDataPassing {
    weak var viewController: MainPageViewController?
    var dataStore: MainPageDataStore?

    func routeToMovieDetail() {
        
        let detailVC = ViewControllers.movieDetail.getViewcontrollers() as! MovieDetailViewController
        var detailDataStore = detailVC.router!.dataStore!
        
        passDataToDetail(source: dataStore!, destination: &detailDataStore)
        navigateToDetail(source: viewController!, destination: detailVC)
    }
    
    // MARK: Navigation
    
    private func navigateToDetail(source: MainPageViewController, destination: MovieDetailViewController) {
        
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    private func passDataToDetail(source: MainPageDataStore, destination: inout MovieDetailDataStore) {
        
        destination.movieID = source.movieID
    }
}
