//
//  MainPageModels.swift
//  Lodos Movies
//
//  Created by Tuğrul on 13.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainPage
{
    // MARK: Use cases

    enum Initialize {

        struct Request { }

        struct Response { }

        struct ViewModel { }
    }
    
    enum Search {

        struct Request { 
            var searchText: String
        }

        struct Response { 
            var isContinue: Bool
            var results: MovieResponse?
        }

        struct ViewModel {
            var isContinue: Bool
            var results: MovieResponse?
        }
    }
    
    enum SelectedMovie {

        struct Request { 
            var movieID: String
        }

        struct Response { }

        struct ViewModel { }
    }
}
