//
//  MainPagePresenter.swift
//  Lodos Movies
//
//  Created by Tuğrul on 13.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainPagePresentationLogic {
    func presentInitializeResult(response: MainPage.Initialize.Response)
    func presentReloadResult(response: MainPage.Reload.Response)
    func presentFinalizeResult(response: MainPage.Finalize.Response)}

class MainPagePresenter: MainPagePresentationLogic {
    weak var viewController: MainPageDisplayLogic?
}

// MARK: - Presentation Logic

extension MainPagePresenter {
    
    func presentInitializeResult(response: MainPage.Initialize.Response) {
        
        viewController?.displayInitializeResult(viewModel: MainPage.Initialize.ViewModel())
    }
    
    func presentReloadResult(response: MainPage.Reload.Response) {
        
        viewController?.displayReloadResult(viewModel: MainPage.Reload.ViewModel())
    }
    
    func presentFinalizeResult(response: MainPage.Finalize.Response) {
        
        viewController?.displayFinalizeResult(viewModel: MainPage.Finalize.ViewModel())
    }
}
