//
//  SplashScreenModels.swift
//  Lodos Movies
//
//  Created by Tuğrul on 13.03.2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

enum SplashScreen {

    // MARK: Use cases

    enum Initialize {

        struct Request { }

        struct Response { 
            var isConnection: Bool
        }

        struct ViewModel { 
            var isConnection: Bool
        }
    }

    enum Reload {

        struct Request { }

        struct Response { }

        struct ViewModel { }
    }

    enum Finalize {

        struct Request { }

        struct Response { }

        struct ViewModel { }
    }
}
